import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/providers/Auth";
import { NotificationsProvider } from "@/providers/Notifications";
import { getSession } from "@/auth/options";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
                                           children
                                         }: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <AuthProvider session={session}>
      <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NotificationsProvider>
          {children}
        </NotificationsProvider>
      </body>
      </html>
    </AuthProvider>
  );
}
