name: "Lint"

run-name: It runs a lint check on the codebase by @${{ github.actor }}

on:
  pull_request:
  push:
    branches:
      - "hotfix/*"

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn lint
